### PR TITLE
Filter indented preprocessor directives

### LINKED ISSUE #316: Error: declaration expected, not `#` on macOS with default cpp
It only happens on macOS with cpp that is bundled in XCode.
Here are codes to reproduce this issue.

- issue.h
```c
#ifndef _ISSUE_H_INCLUDED_
#define _ISSUE_H_INCLUDED_


#define DEF_VAL 0

#endif
```

- issue.dpp
```d
#include "issue.h"

void main() {}
```

## How to reproduce
```console
$ dub run -q dpp -- --ignore-system-paths --preprocess-only issue.dpp
$ dmd -run issue.d
```

## Expected behavior
The above commands are successfully executed.

## Actual behavior
`dmd -run` fails with the following messages:
```console
$ dmd -run issue.d
issue.d(57): Error: declaration expected, not `#`
issue.d(67): Error: unmatched closing brace
```

## Note
I reproduce it on Github Actions with [this configuration](https://github.com/tom-tan/dpp/blob/4de6685e4d80b6c99c65a5e3c57d13fe17dbb279/.github/workflows/d.yml).
Here is a difference between `clang-cpp` (used in Github Actions for dpp) and `/usr/bin/cpp` (default cpp on Github Actions).

- preprocessed by `clang-cpp` ([result of Github Actions](https://github.com/tom-tan/dpp/runs/8076609574?check_suite_focus=true#step:9:76))
```d
...
extern(C)
{





    static if(!is(typeof(DEF_VAL))) {
        private enum enumMixinStr_DEF_VAL = `enum DEF_VAL = 0;`;
        static if(is(typeof({ mixin(enumMixinStr_DEF_VAL); }))) {
            mixin(enumMixinStr_DEF_VAL);
        }
    }

}
...
```

- preprocessed by `cpp` ([result of Github Actions](https://github.com/tom-tan/dpp/runs/8076609723?check_suite_focus=true#step:6:67))
```d
...
extern(C)
{
    
    
    #ifdef DEF_VAL
    
    #endif
    static if(!is(typeof(DEF_VAL))) {
        private enum enumMixinStr_DEF_VAL = `enum DEF_VAL = 0;`;
        static if(is(typeof({ mixin(enumMixinStr_DEF_VAL); }))) {
            mixin(enumMixinStr_DEF_VAL);
        }
    }
    
}
...
```

It would be nice if dpp can work with `/usr/bin/cpp`.

### PR DESCRIPTION
**Pull request by tom-tan**
It fixes #316 by modifying filtering rule for the output of `cpp -w --comments`.

I'm not sure how to add tests for it because it cannot be reproduced with current Github Actions configuration with `clang-cpp`.
Do you have any idea for it?

### CODE REVIEW

File: source/dpp/runtime/app.d [hunk 1]
```diff
@@ -277,7 +278,7 @@ private void runCPreProcessor(in string cppPath, in string tmpFileName, in strin
         auto lines = ret.
             output
             .splitLines
-            .filter!(a => !a.startsWith("#"))
```
Comment (atilaneves) [inline source/dpp/runtime/app.d:280]: Maybe better to filter if it has `#` in it at all.

Comment (tom-tan) [reply source/dpp/runtime/app.d:280]: It accidentally filters the lines such as `"This string contains # but it must not be filtered"`.

Comment (atilaneves) [reply source/dpp/runtime/app.d:280]: Ah, I see.

**Review by atilaneves — APPROVED** [review]

**Comment by tom-tan** [comment]
Thanks!
